In [1]:
#Q1
import numpy as np

# 创建从1到12的一维数组
arr = np.arange(1, 13)

# 重塑为3行4列二维数组
arr = arr.reshape(3, 4)

# 输出数组
print("数组：")
print(arr)

# 输出数组属性
print("维度:", arr.ndim)
print("形状:", arr.shape)
print("元素总个数:", arr.size)

数组：
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
维度: 2
形状: (3, 4)
元素总个数: 12


In [2]:
import numpy as np

# 创建浮点数数组
arr = np.array([1.5, 2.6, 3.7, 4.8])

# 转换为int32类型
arr_int = arr.astype(np.int32)

# 输出结果
print("转换前数组:", arr)
print("转换前数据类型:", arr.dtype.name)

print("转换后数组:", arr_int)
print("转换后数据类型:", arr_int.dtype.name)

转换前数组: [1.5 2.6 3.7 4.8]
转换前数据类型: float64
转换后数组: [1 2 3 4]
转换后数据类型: int32


In [3]:
import numpy as np

# 创建二维数组
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# 获取前两行，第2到第3列
result = arr[:2, 1:3]

# 输出结果
print(result)

[[2 3]
 [6 7]]


In [4]:
import numpy as np

# 创建数组
arr = np.array([10, 15, 20, 25, 30, 35])

# 花式索引
fancy_result = arr[[0, 2, 4]]

# 布尔索引
bool_result = arr[arr > 20]

# 输出结果
print("花式索引结果:", fancy_result)
print("布尔索引结果:", bool_result)

花式索引结果: [10 20 30]
布尔索引结果: [25 30 35]


In [5]:
import numpy as np

# 创建全0数组
arr_a = np.zeros((3, 4))

# 创建一维数组
arr_b = np.array([1, 2, 3, 4])

# 广播相加
result = arr_a + arr_b

# 输出结果
print(result)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [6]:
import numpy as np

# 创建数组
x = np.array([1, 4, 9, 16])
y = np.array([2, 1, 4, 5])

# 计算平方根
sqrt_result = np.sqrt(x)

print("平方根结果:", sqrt_result)

# 求对应位置最大值
max_result = np.maximum(sqrt_result, y)

print("对应位置最大值:", max_result)

平方根结果: [1. 2. 3. 4.]
对应位置最大值: [2. 2. 4. 5.]


In [7]:
import numpy as np

# 创建三维数组
arr = np.arange(24).reshape((2, 3, 4))

# 转置
new_arr = arr.transpose((1, 0, 2))

# 输出新形状
print("转换后数组形状:", new_arr.shape)

转换后数组形状: (3, 2, 4)


In [8]:
import numpy as np

# 创建数组
arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
arr_con = np.array([True, False, True])

# 条件选择
result = np.where(arr_con, arr_x, arr_y)

# 输出结果
print(result)

[1 6 7]


In [9]:
import numpy as np

# 创建二维数组
arr = np.array([
    [6, 2, 7],
    [3, 6, 2],
    [4, 3, 2]
])

# 计算平均值
mean_value = arr.mean()

# 按列排序
sorted_arr = np.sort(arr, axis=0)

# 输出结果
print("平均值:", mean_value)

print("按列排序后:")
print(sorted_arr)

平均值: 3.888888888888889
按列排序后:
[[3 2 2]
 [4 3 2]
 [6 6 7]]


In [10]:
import numpy as np

# 设置随机数种子
np.random.seed(10)

# 生成随机矩阵
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)

# 计算点积
result = np.dot(A, B)

# 输出结果
print("矩阵A:")
print(A)

print("矩阵B:")
print(B)

print("点积结果:")
print(result)

矩阵A:
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]]
矩阵B:
[[0.49850701 0.22479665]
 [0.19806286 0.76053071]]
点积结果:
[[0.38861894 0.18917279]
 [0.46418833 0.71193035]]
